site_name: Aizen Documentation
site_description: Aizen, Autonomous web3 agents with powerful tools and realtime data
site_url: https://docs.aizen.ai
repo_url: https://github.com/redaicodes/aizen
repo_name: redaicodes/aizen
# docs_dir: docs/md_v2

nav:
  - Home: 'index.md'
  - 'Installation': 'basic/installation.md'
  - 'Quick Start': 'basic/quickstart.md'
  
  - Basics:
    - 'What are Tools?': 'basic/what-are-tools.md'
    - 'Importance of Right Data': 'basic/importance-of-right-data.md'
    - 'Taking Actions': 'basic/taking-actions.md'
    
  - API Reference:
    - 'agents': 'api/agents.md'
    - 'data': 'api/data.md'
    - 'protocols': 'api/protocols.md'

  - Tutorial:
    - '1. Getting Started': 'tutorial/episode_01_Introduction_to_Crawl4AI_and_Basic_Installation.md'
    - '2. Advanced Features': 'tutorial/episode_02_Overview_of_Advanced_Features.md'
    - '3. Browser Setup': 'tutorial/episode_03_Browser_Configurations_&_Headless_Crawling.md'

theme:
  name: terminal
  palette: dark

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - tables

extra_css:
  - assets/styles.css
  - assets/highlight.css
  - assets/dmvendor.css

extra_javascript:
  - assets/highlight.min.js
  - assets/highlight_init.js