site_name: Aizen Documentation
site_description: Aizen, Autonomous web3 agents with powerful tools and realtime data
site_url: https://docs.aizen.ai
repo_url: https://github.com/redaicodes/aizen
repo_name: redaicodes/aizen

nav:
    - Introduction: "index.md"
    - Getting Started:
          - "Installation & Setup": "getting-started/installation.md"
          - "Quick Start Guide": "getting-started/quickstart.md"

    - Core Concepts:
          - "Next Gen AI Agents": "concepts/next-gen-agents.md"
          - "Platform Features": "concepts/features.md"

    - Examples:
          - "Real World Applications": "examples/applications.md"
          - "Agent Examples": "examples/agent-examples.md"

    - Development:
          - "Why Python": "development/python-ecosystem.md"
          - "Contributing": "development/contributing.md"

theme:
    name: terminal
    palette: dark
    features:
        - content.code.copy
        - content.code.select
        - content.code.annotate

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - admonition
    - pymdownx.details
    - attr_list
    - md_in_html
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - tables
    - def_list
    - pymdownx.tasklist:
          custom_checkbox: true
    - toc:
          permalink: true

extra_css:
    - assets/styles.css
    - assets/highlight.css
    - assets/dmvendor.css

extra_javascript:
    - assets/highlight.min.js
    - assets/highlight_init.js

plugins:
    - search
    - minify:
          minify_html: true

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/redaicodes/aizen
