site_name: Aizen Documentation
site_description: Web3 AI Agent Platform with powerful tools and realtime data
repo_url: https://github.com/redaicodes/aizen

theme:
    name: material
    palette:
        scheme: slate
        primary: teal
        accent: teal
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.sections
        - navigation.tabs
        - toc.follow
        - content.code.copy
    font:
        text: Roboto Mono
        code: Roboto Mono
    icon:
        logo: material/robot
        repo: fontawesome/brands/github

nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - Platform: platform.md
    - Examples: examples.md

plugins:
    - search

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.tasklist:
          custom_checkbox: true
    - tables
    - attr_list
    - md_in_html
    - def_list
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/redaicodes/aizen
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/redaicodes

extra_css:
    - stylesheets/extra.css
